pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

//include ':launcher'
include ':unityLibrary'
include ':MainApp.androidlib'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()

        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}

includeBuild("../sentry-java") {
    dependencySubstitution {
        substitute(module("io.sentry:sentry")).using(project(":sentry"))
        substitute(module("io.sentry:sentry-android-core")).using(project(":sentry-android-core"))
        substitute(module("io.sentry:sentry-android-ndk")).using(project(":sentry-android-ndk"))
    }
}
