apply plugin: 'com.android.application'
apply from: 'setupSymbols.gradle'
apply from: '../shared/keepUnitySymbols.gradle'

dependencies {
    implementation project(':unityLibrary')
}

android {
    namespace "com.DefaultCompany.UaaLExample"
    ndkPath "/Applications/Unity/Hub/Editor/6000.0.25f1/PlaybackEngines/AndroidPlayer/NDK"
    ndkVersion "23.1.7779620"
    compileSdk 35
    buildToolsVersion = "34.0.0"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId "com.DefaultCompany.UaaLExample"
        versionName "0.1"
        minSdk 23
        targetSdk 35
        versionCode 1

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
            debugSymbolLevel "none"
        }
    }

    lint {
        abortOnError false
    }

    androidResources {
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
        noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }

    buildTypes {
        debug {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            jniDebuggable = true
            signingConfig signingConfigs.debug
        }

        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.debug
        }
    }

    androidComponents {
        onVariants(selector().all(), { variant ->
            variant.bundleConfig.addMetadataFile(
                "com.unity",
                project.layout.file(project.providers.provider { new File("dependencies.pb") })
            )
            variant.bundleConfig.addMetadataFile(
                "com.unity",
                project.layout.file(project.providers.provider { new File("app-metadata.properties") })
            )
        })
    }

    bundle {
        language {
            enableSplit = false
        }

        density {
            enableSplit = false
        }

        abi {
            enableSplit = true
        }

        texture {
            enableSplit = true
        }
    }
}// Autogenerated Sentry symbol upload task [start]
// Credentials and project settings information are stored in the sentry.properties file
afterEvaluate {
task sentryUploadSymbols {
    doLast {
        println 'Uploading symbols to Sentry.'
        exec {
            environment 'SENTRY_PROPERTIES', './sentry.properties'
            executable './sentry-cli-Darwin-universal'
            args = ['debug-files', 'upload', '--il2cpp-mapping', project.rootDir]
        }
    }
}

tasks.assembleDebug.finalizedBy sentryUploadSymbols
tasks.assembleRelease.finalizedBy sentryUploadSymbols
tasks.bundleDebug.finalizedBy sentryUploadSymbols
tasks.bundleRelease.finalizedBy sentryUploadSymbols
}
// Autogenerated Sentry symbol upload task [end]
